name: '[PR] Closed test'

on:
  pull_request:
    types: [closed]
    branches:
      - '**'
      - '!changeset-release/**'

jobs:
  pr-closed:
   name: Test PR closed
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v4