name: '[PR] Closed test'

on:
  pull_request:
    types: [closed]

jobs:
  check:
    if: ${{ !startsWith(github.event.pull_request.head.ref, 'changeset-release/') }}
    name: Check workflow
    runs-on: ubuntu-latest

  pr-closed:
   needs: check
   name: Test PR closed
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display PR information
        run: |
          echo "Ref ${{ github.event.pull_request.head.ref }}"
  
  test:
    needs: pr-closed
    name: Test job
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4