name: '[PR] Closed test'

on:
  pull_request:
    types: [closed]

jobs:
  pr-closed:
   name: Test PR closed
   runs-on: ubuntu-latest
   if: ${{ !startsWith(github.event.pull_request.head.ref, 'changeset-release/') }}
   steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Display PR information
        run: |
          echo "Ref ${{ github.event.pull_request.head.ref }}"
  
  test:
    needs: pr-closed
    name: Test job
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4